raw_data_config: 
  raw_data_csv: ../data/raw/column_3C.csv
  model_var: ["pelvic_incidence", "pelvic_tilt", "lumbar_lordosis_angle", "sacral_slope","pelvic_radius","degree_spondylolisthesis","label"]
  train_test_split_ratio: 0.3
  target: label 
  random_state: 111
  new_train_data_csv: ../data/raw/train.csv
  
data_source:
  url : 'https://archive.ics.uci.edu/ml/machine-learning-databases/00212/vertebral_column_data.zip'

processed_data_config:
  train_data_csv: ../data/processed/train.csv
  test_data_csv:  ../data/processed/test.csv

model_choice:
  # random_forest or knn
  #model: 'knn'
  model: 'random_forest'

random_forest: 
  max_depth: 5
  n_estimators: 5

knn: 
  n_neighbors: 100

mlflow_global_config:
  artifacts_dir: artifacts
  experiment_name: vertebral
  registered_model_name: vertebral_fr_run1
  remote_server_uri: http://localhost:1234

mlflow_random_forest_config:
  run_name: random_forest
  

mlflow_knn_config:
  run_name: knn
# Modèle   
model_dir: ../models/model.joblib


model_webapp_dir: ./webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: label
monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
